apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-games-deployment
  namespace: go-games
  labels:
    app: go-games
spec:
  replicas: 2
  selector:
    matchLabels:
      app: go-games
  template:
    metadata:
      labels:
        app: go-games
    spec:
      containers:
      - name: go-games
        image: <YOUR-GITHUB-USERNAME>/go-games-api
---
apiVersion: v1
kind: Service
metadata:
  name: go-games-service
  namespace: go-games
spec:
  type: NodePort
  selector:
    app: go-games
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080  
      nodePort: 30080

---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: go-games-ingress
  namespace: go-games
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: go-games-service
            port:
              number: 80
